sudo: required

language: ruby
services:
  - docker
  
before_install:
- docker pull selenium/standalone-chrome
- docker run -d -p 4444:4444 selenium/standalone-chrome

script:
- ruby ruby_testcase.rb
